export const images: string[] = [
  '/Ayoub.jpeg',
  '/Elhaw.jpeg',
  '/Adel.jpg',
  '/Twfiek.jpeg',
  '/Omar.jpg',
  '/Sayad.jpg',
  '/Essam.jpg',
  '/Sahl.jpeg',
  '/Samy.jpeg',
  '/Shaf3y.jpeg',
  '/Ali.jpeg',
  '/Amr.jpeg',
  '/Seif.jpeg',
];
