name: deploy pickly-frontend dev to m3ntorship-dev cluster

# trigger
on:
  push:
    branches:
      - deployment
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      name: ${{ steps.version.outputs.ahmed }}
    steps:
      - uses: actions/checkout@v2
      # dynamic deployment envs
      - name: set templating envs
        id: version
        run: |
          echo ::set-output name=version::dev-$(git rev-parse --short=4 ${{ github.sha }})
          echo ::set-output name=ahmed::nile
      - name: set templating envs
        id: test
        run: |
          echo ${{ steps.version.outputs.version }}
          echo ${{ steps.version.outputs.name }}
  # test:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: set templating envs
  #       id: version
  #       run: |
  #         echo ${{ needs.prepare.outputs.version }}
  #         echo ${{ needs.prepare.outputs.name }}
          
      